# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: becf57ae1339d0658d66e042b443bbf0614bb47395c4e490938f6b0f9cf59046d1095c53361df2ae80864798c089d5a34335e29fbcd4b9d44d01de2cf8a164b0

test:
  secret_key_base: 77442bde0e1c15cba78a1d385faedf863b6056e53b64b9f2d06ce620c37813d4416f85e078ae66131c8fd2d4cab559444ab6fb1e7edcafa202f47a2a5c50aab6

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
